module.exports = {
  URL: 'https://mail.yandex.by/',
  USER_NAME: 'test1ng7',
  PASSWORD: '123456789a',
  WRONG_NAME: 'te786st',
  WAIT: 'wait',
  COLOR: 'color',
  COLOR_ERROR: 'rgba(223, 75, 65, 1)',
  BGC_ERROR: 'rgba(230, 21, 21, 0.1)',
  TINE_WAIT_PAGE: 25000,
  TIME_WAIT: 5000,
  MAIN_BUTTON: 'a.HeadBanner-Button-Enter',
  SUBMIT: 'button[type="submit"]',
  LOGIN_FIELD: 'passp-field-login',
  PASSWORD_FIELD: 'passp-field-passwd',
  FOCUSE_FIELD: 'passp-form-field_focused',
  MAIL_USER_NAME: 'mail-User-Name',
  A: 'a',
  FORM_FIELD_ERROR: 'div.passp-form-field__error',
  WRITE_LETTER: 'a[href="#compose"]',
  REFRESH: '.mail-ComposeButton-Refresh.js-main-action-refresh.ns-action',
  SENT: 'a[href="#sent"]',
  BGC: 'background-color',
  BGC_CHOSE_SENT: 'rgba(107, 135, 175, 0.2)',
  UNTIL: 'until',
  WHOME_NAME: 'div[name="to"]',
  TEST: 'test',
  WHOME_NAME_ERROR: 'ns-view-compose-field-to-error',
  BODY_LETTER: 'The letter for you, my frind',
  EMAIL: 'test1ng7@yandex.ru',
  WHOME_NAME_CLICK: '.js-contact-bubble.mail-Bubble-Contact.js-bubble.mail-Bubble',
  WHOME_NAME_REMOVE: '.b-mail-dropdown__item__content.js-bubble-remove',
  WHOLE_NAME_VALUE: 'span[data-yabble-name="test1ng7"]',
  DONE: 'Done',
  DONE_REG: /(D|d)one/g,
  TITLE_DONE: 'js-title-info',
  CLASS_NAME: 'class',
  DELETE_ICON: '.js-toolbar-item-delete .svgicon-mail--MainToolbar-Delete',
  DELETE_COLOR: 'rgba(230, 80, 80, 1)',
  BTN_DELETE: 'js-toolbar-item-delete',
  CHECKBOX: '._nb-checkbox-flag._nb-checkbox-normal-flag',
  WIDTH_WRITE: '36px',
  W: 'w',
};
